### Запуск кода (id - идентификатор запроса, code - код, language - язык, image - образ)
POST http://localhost:8080/api/run
Content-Type: application/json

{
  "id": 0,
  "code": "package main\n\nimport \"fmt\"\n\nfunc main() {\n\treturn \"Hello world!\"\n}",
  "language": "golang",
  "image": "golang:1.24"
}
